# config/prometheus.yml (CORREGIDO)
global:
  scrape_interval: 15s

scrape_configs:
  # 1. Job para monitorear los contenedores (CPU, RAM, Red)
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'cadvisor' # <--- ¡ESTA ES LA LÍNEA QUE FALTABA!

  # 2. Job para monitorear PostgreSQL
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['pg_exporter:9187']